### ISSUE TITLE
Ambiguous semantics on "Become a validator" page

### ISSUE THREAD

**Issue by DaveWK** [KYVENetwork/docs#44]
On the "Become a validator" there's some ambiguous wording which is confusing:

https://github.com/KYVENetwork/docs/blob/main/docs/validators/chain_nodes/become_validator.md?plain=1#L44

```Before creating a validator you need two keys. One key is for managing your validator and keeping your funds. The other one is only for signing blocks. In case the latter gets compromised you only risk a slash but not loosing your entire funds.```

Then there is 2 paragraphs about the "Private Node Key" and "Operating Key". The wording does not make it clear which of these keys is responsible for which of these operations. 

Additionally, under the "The Create-Validator transaction" section it discusses making a "key" -- in this context it is too ambiguous which "key" is being referred to. Generally I would suggest never referring to anything involved in a process with this many "keys" to not specify which "key" is being referred to.

**Comment by mbreithecker** [comment]
Hey @DaveWK ,
thanks for your input. We will make this section more clear.
