### ISSUE TITLE
Contributing Guide

### ISSUE THREAD

**Issue by Mackenzie-OO7** [KYVENetwork/docs#61]
I noticed that there is no contributing guide in this repo. Is there a reason for that? If not, can I write one and have it reviewed?

**Comment by abdallacodes** [comment]
This was discussed at some point in the past:
[#1518](https://github.com/giuspen/cherrytree/issues/1518)

**Comment by Mackenzie-OO7** [comment]
> This was discussed at some point in the past: [#1518](https://github.com/giuspen/cherrytree/issues/1518)

Okay, thanks! 
If no one is working on it, I'd be happy to do that :)
